spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernatediving
    username: db_user
    password: db_user_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
