spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernatediving
    username: db_user
    password: db_user_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

